services:
  - type: web
    name: minecraft-server
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SERVER_PORT
        value: 25565
      - key: MAX_PLAYERS
        value: 20
      - key: ONLINE_MODE
        value: false
      - key: MOTD
        value: "Minecraft Server on Render"
      - key: WORLD_NAME
        value: "world"
      - key: GAMEMODE
        value: "survival"
      - key: DIFFICULTY
        value: "normal"
    healthCheckPath: /
    autoDeploy: true
    plan: starter 